Par 1778 display changes to legal entities on the partnership page
UKGovernmentBEIS/beis-primary-authority-register pull request #853
Opened 2022-08-22 08:03 UTC by RogerBailey

2022-08-22 12:43 UTC, kalpaitch requested changes

2022-08-22 12:43 UTC, kalpaitch commented on web/modules/custom/par_data/src/Entity/ParDataPartnershipLegalEntity.php
>    public function getStartDate() {
@RogerBailey Is this returning a datetime object, a timestamp or a rendered date? I think it could be useful to specify the return type...

2022-08-22 12:43 UTC, kalpaitch commented on web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_direct.yml
> +      partnership_legal_entity_display:
Cool, we'll also need to update the config in the sync folder I think: `sync/par_flows.par_flow.partnership_direct.yml`

There are also a few other journeys where this might need to be updated:

- `par_flows.par_flow.partnership_coordinated.yml`
- `par_flows.par_flow.partnership_authority.yml`
- `par_flows.par_flow.search_partnership.yml`

Note: I think the fact we have so many different places we display partnership information is problematic in it's own way and will eventually need to look at this too.

2022-08-22 12:43 UTC, kalpaitch commented on web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
> +    if (isset($partnership_legal_entities) && !empty ($partnership_legal_entities)) {
We might not need this conditional, the `getPartnershipLegalEntity()` method without any parameters always returns an array, we could move L40 to below L37 (whether it's empty or not, the default value below is an empty array anyway).

2022-08-22 12:43 UTC, kalpaitch commented on web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
> +            '#value' => $start_date->format('d M Y'),
If we could format all dates according with the GDS date format that would be fantastic (`getDateFormatter()` returns DateFormatterInterface => `\Drupal::service('date.formatter')`)
```
$this->getDateFormatter()->format($start_date, 'gds_date_format');
```

2022-08-22 12:43 UTC, kalpaitch commented on web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
> +      if ($partnership->isActive()) {
Nice, that seems sensible.

2022-08-22 15:05 UTC, RogerBailey commented on web/modules/custom/par_data/src/Entity/ParDataPartnershipLegalEntity.php
>    public function getStartDate() {
Have added @return entries to DocBlock comments for 'getter' methods.

2022-08-23 10:16 UTC, RogerBailey commented on web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
> +    if (isset($partnership_legal_entities) && !empty ($partnership_legal_entities)) {
Removed the conditional.

2022-08-23 10:17 UTC, RogerBailey commented on web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_direct.yml
> +      partnership_legal_entity_display:
Updated yml in sync to match yml in feature.

2022-08-23 11:22 UTC, RogerBailey commented on web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
> +            '#value' => $start_date->format('d M Y'),
Changed code to use date.formatter service to output dates.

2022-08-24 07:27 UTC, RogerBailey commented on web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
> +            '#value' => $start_date->format('d M Y'),
Done.

2022-08-31 15:24 UTC, merged