PAR-2136
UKGovernmentBEIS/beis-primary-authority-register pull request #957
Opened 2023-04-27 16:23 UTC by ThommCroft

Updated the Help Desk manage people tests and cleaned up related Page object classes.

2023-04-28 10:49 UTC, ndileonel commented on tests/e2e/par-test-automation/src/main/java/uk/gov/beis/pageobjects/AddPersonContactDetailsPage.java
> -	public void enterTitle(String title) {
Rename AddPersonContactDetailsPage to PersonContactDetailsPage OR UserContactDetailsPage

2023-04-28 13:48 UTC, ndileonel requested changes

2023-04-28 17:21 UTC, ThommCroft commented on tests/e2e/par-test-automation/src/main/java/uk/gov/beis/pageobjects/AddPersonContactDetailsPage.java
>  public class AddPersonContactDetailsPage extends BasePageObject {
Changed to PersonContactDetailsPage

2023-04-28 17:22 UTC, ThommCroft commented on tests/e2e/par-test-automation/src/main/java/uk/gov/beis/pageobjects/GivePersonAccountPage.java
>  public class GivePersonAccountPage extends BasePageObject {
Done

2023-05-05 21:25 UTC, ndileonel approved these changes

2023-05-07 07:42 UTC, merged